[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
RAILWAY_BUILD_VERSION = "1.0.2"
DEPLOY_TIMESTAMP = "2025-08-19T13:15:00Z"
